### ISSUE TITLE
Is the part 'How to generate headers' actual?

### ISSUE THREAD

**Issue by astrochili** [d954mas/IntelliJ-Defold-Api#3]
Hi! Thanks for the api.

> 1)Download jar from [releases](https://github.com/d954mas/IntelliJ-Defold-Api/releases)
> 2)Run it. It will create a folder DefoldDocs
> 3)Compress DefoldDocs/api to zip

This instruction sounds a little unclear, which jar file I should run? Do I need anything else besides Java?

**Comment by d954mas** [comment]
Hi) 
Sorry I not build jar for releases.

1)you need clone repo
2) run main method from Main.java

**Comment by d954mas** [comment]
Update api to 1.3.3
Fixed readme
